/*
 * MovieApp
 * MovieApp description.
 *
 * OpenAPI spec version: 0.5.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.wsb.students.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * ChangePasswordRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-06-16T17:00:47.790Z")
public class ChangePasswordRequest   {
  @JsonProperty("email")
  private String email = null;

  @JsonProperty("oldpassword")
  private String oldpassword = null;

  @JsonProperty("newpassword")
  private String newpassword = null;

  public ChangePasswordRequest email(String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   **/
  @JsonProperty("email")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public ChangePasswordRequest oldpassword(String oldpassword) {
    this.oldpassword = oldpassword;
    return this;
  }

  /**
   * Get oldpassword
   * @return oldpassword
   **/
  @JsonProperty("oldpassword")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getOldpassword() {
    return oldpassword;
  }

  public void setOldpassword(String oldpassword) {
    this.oldpassword = oldpassword;
  }

  public ChangePasswordRequest newpassword(String newpassword) {
    this.newpassword = newpassword;
    return this;
  }

  /**
   * Get newpassword
   * @return newpassword
   **/
  @JsonProperty("newpassword")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public String getNewpassword() {
    return newpassword;
  }

  public void setNewpassword(String newpassword) {
    this.newpassword = newpassword;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePasswordRequest changePasswordRequest = (ChangePasswordRequest) o;
    return Objects.equals(this.email, changePasswordRequest.email) &&
        Objects.equals(this.oldpassword, changePasswordRequest.oldpassword) &&
        Objects.equals(this.newpassword, changePasswordRequest.newpassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, oldpassword, newpassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePasswordRequest {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    oldpassword: ").append(toIndentedString(oldpassword)).append("\n");
    sb.append("    newpassword: ").append(toIndentedString(newpassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

